apiVersion: v1
kind: Service
metadata:
  name: trino-coordinator-service
  namespace: k9s-trino-oracledatabase-airflow
spec:
  selector:
    app: trino1
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8085
  type: ClusterIP
